/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardTodosRouteImport } from './routes/dashboard/todos'
import { Route as DashboardMapsRouteImport } from './routes/dashboard/maps'
import { Route as DashboardBetterAuthRouteImport } from './routes/dashboard/better-auth'
import { Route as DashboardUserPermissionsRouteImport } from './routes/dashboard/user.permissions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/dashboard/users',
  path: '/dashboard/users',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTodosRoute = DashboardTodosRouteImport.update({
  id: '/dashboard/todos',
  path: '/dashboard/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMapsRoute = DashboardMapsRouteImport.update({
  id: '/dashboard/maps',
  path: '/dashboard/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBetterAuthRoute = DashboardBetterAuthRouteImport.update({
  id: '/dashboard/better-auth',
  path: '/dashboard/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUserPermissionsRoute =
  DashboardUserPermissionsRouteImport.update({
    id: '/dashboard/user/permissions',
    path: '/dashboard/user/permissions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/better-auth': typeof DashboardBetterAuthRoute
  '/dashboard/maps': typeof DashboardMapsRoute
  '/dashboard/todos': typeof DashboardTodosRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/user/permissions': typeof DashboardUserPermissionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/better-auth': typeof DashboardBetterAuthRoute
  '/dashboard/maps': typeof DashboardMapsRoute
  '/dashboard/todos': typeof DashboardTodosRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/user/permissions': typeof DashboardUserPermissionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/better-auth': typeof DashboardBetterAuthRoute
  '/dashboard/maps': typeof DashboardMapsRoute
  '/dashboard/todos': typeof DashboardTodosRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/user/permissions': typeof DashboardUserPermissionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/better-auth'
    | '/dashboard/maps'
    | '/dashboard/todos'
    | '/dashboard/users'
    | '/dashboard/user/permissions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/better-auth'
    | '/dashboard/maps'
    | '/dashboard/todos'
    | '/dashboard/users'
    | '/dashboard/user/permissions'
  id:
    | '__root__'
    | '/'
    | '/dashboard/better-auth'
    | '/dashboard/maps'
    | '/dashboard/todos'
    | '/dashboard/users'
    | '/dashboard/user/permissions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardBetterAuthRoute: typeof DashboardBetterAuthRoute
  DashboardMapsRoute: typeof DashboardMapsRoute
  DashboardTodosRoute: typeof DashboardTodosRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardUserPermissionsRoute: typeof DashboardUserPermissionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/dashboard/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/todos': {
      id: '/dashboard/todos'
      path: '/dashboard/todos'
      fullPath: '/dashboard/todos'
      preLoaderRoute: typeof DashboardTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/maps': {
      id: '/dashboard/maps'
      path: '/dashboard/maps'
      fullPath: '/dashboard/maps'
      preLoaderRoute: typeof DashboardMapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/better-auth': {
      id: '/dashboard/better-auth'
      path: '/dashboard/better-auth'
      fullPath: '/dashboard/better-auth'
      preLoaderRoute: typeof DashboardBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/user/permissions': {
      id: '/dashboard/user/permissions'
      path: '/dashboard/user/permissions'
      fullPath: '/dashboard/user/permissions'
      preLoaderRoute: typeof DashboardUserPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardBetterAuthRoute: DashboardBetterAuthRoute,
  DashboardMapsRoute: DashboardMapsRoute,
  DashboardTodosRoute: DashboardTodosRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardUserPermissionsRoute: DashboardUserPermissionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
