/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardTodosRouteImport } from './routes/dashboard/todos'
import { Route as DashboardRolesRouteImport } from './routes/dashboard/roles'
import { Route as DashboardPermissionsRouteImport } from './routes/dashboard/permissions'
import { Route as DashboardMapsRouteImport } from './routes/dashboard/maps'
import { Route as DashboardBetterAuthRouteImport } from './routes/dashboard/better-auth'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/dashboard/users',
  path: '/dashboard/users',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTodosRoute = DashboardTodosRouteImport.update({
  id: '/dashboard/todos',
  path: '/dashboard/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRolesRoute = DashboardRolesRouteImport.update({
  id: '/dashboard/roles',
  path: '/dashboard/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPermissionsRoute = DashboardPermissionsRouteImport.update({
  id: '/dashboard/permissions',
  path: '/dashboard/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMapsRoute = DashboardMapsRouteImport.update({
  id: '/dashboard/maps',
  path: '/dashboard/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBetterAuthRoute = DashboardBetterAuthRouteImport.update({
  id: '/dashboard/better-auth',
  path: '/dashboard/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/better-auth': typeof DashboardBetterAuthRoute
  '/dashboard/maps': typeof DashboardMapsRoute
  '/dashboard/permissions': typeof DashboardPermissionsRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/todos': typeof DashboardTodosRoute
  '/dashboard/users': typeof DashboardUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/better-auth': typeof DashboardBetterAuthRoute
  '/dashboard/maps': typeof DashboardMapsRoute
  '/dashboard/permissions': typeof DashboardPermissionsRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/todos': typeof DashboardTodosRoute
  '/dashboard/users': typeof DashboardUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/better-auth': typeof DashboardBetterAuthRoute
  '/dashboard/maps': typeof DashboardMapsRoute
  '/dashboard/permissions': typeof DashboardPermissionsRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/todos': typeof DashboardTodosRoute
  '/dashboard/users': typeof DashboardUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/better-auth'
    | '/dashboard/maps'
    | '/dashboard/permissions'
    | '/dashboard/roles'
    | '/dashboard/todos'
    | '/dashboard/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/better-auth'
    | '/dashboard/maps'
    | '/dashboard/permissions'
    | '/dashboard/roles'
    | '/dashboard/todos'
    | '/dashboard/users'
  id:
    | '__root__'
    | '/'
    | '/dashboard/better-auth'
    | '/dashboard/maps'
    | '/dashboard/permissions'
    | '/dashboard/roles'
    | '/dashboard/todos'
    | '/dashboard/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardBetterAuthRoute: typeof DashboardBetterAuthRoute
  DashboardMapsRoute: typeof DashboardMapsRoute
  DashboardPermissionsRoute: typeof DashboardPermissionsRoute
  DashboardRolesRoute: typeof DashboardRolesRoute
  DashboardTodosRoute: typeof DashboardTodosRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/dashboard/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/todos': {
      id: '/dashboard/todos'
      path: '/dashboard/todos'
      fullPath: '/dashboard/todos'
      preLoaderRoute: typeof DashboardTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/roles': {
      id: '/dashboard/roles'
      path: '/dashboard/roles'
      fullPath: '/dashboard/roles'
      preLoaderRoute: typeof DashboardRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/permissions': {
      id: '/dashboard/permissions'
      path: '/dashboard/permissions'
      fullPath: '/dashboard/permissions'
      preLoaderRoute: typeof DashboardPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/maps': {
      id: '/dashboard/maps'
      path: '/dashboard/maps'
      fullPath: '/dashboard/maps'
      preLoaderRoute: typeof DashboardMapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/better-auth': {
      id: '/dashboard/better-auth'
      path: '/dashboard/better-auth'
      fullPath: '/dashboard/better-auth'
      preLoaderRoute: typeof DashboardBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardBetterAuthRoute: DashboardBetterAuthRoute,
  DashboardMapsRoute: DashboardMapsRoute,
  DashboardPermissionsRoute: DashboardPermissionsRoute,
  DashboardRolesRoute: DashboardRolesRoute,
  DashboardTodosRoute: DashboardTodosRoute,
  DashboardUsersRoute: DashboardUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
