// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { DeleteApiV1AccountsData, DeleteApiV1AccountsResponses, DeleteApiV1GeoNotesData, DeleteApiV1GeoNotesResponses, GetApiV1PermissionsData, GetApiV1PermissionsResponses, GetApiV1RolesData, GetApiV1RolesResponses, DeleteApiV1TodosData, DeleteApiV1TodosResponses, GetApiV1UserData, GetApiV1UserResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class AccountsService {
    public static <ThrowOnError extends boolean = true>(options: Options<DeleteApiV1AccountsData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<DeleteApiV1AccountsResponses, unknown, ThrowOnError>({
            url: '/api/v1/accounts',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class GeoNotesService {
    public static <ThrowOnError extends boolean = true>(options: Options<DeleteApiV1GeoNotesData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<DeleteApiV1GeoNotesResponses, unknown, ThrowOnError>({
            url: '/api/v1/geo-notes',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class PermissionsService {
    public static <ThrowOnError extends boolean = true>(options?: Options<GetApiV1PermissionsData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetApiV1PermissionsResponses, unknown, ThrowOnError>({
            url: '/api/v1/permissions',
            ...options
        });
    }
}

export class RolesService {
    public static <ThrowOnError extends boolean = true>(options?: Options<GetApiV1RolesData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetApiV1RolesResponses, unknown, ThrowOnError>({
            url: '/api/v1/roles',
            ...options
        });
    }
}

export class TodosService {
    public static <ThrowOnError extends boolean = true>(options: Options<DeleteApiV1TodosData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<DeleteApiV1TodosResponses, unknown, ThrowOnError>({
            url: '/api/v1/todos',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class UserService {
    public static <ThrowOnError extends boolean = true>(options?: Options<GetApiV1UserData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetApiV1UserResponses, unknown, ThrowOnError>({
            url: '/api/v1/user',
            ...options
        });
    }
}