// This file is auto-generated by @hey-api/openapi-ts

export type DeleteApiV1AccountsData = {
    body: {
        userId: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/accounts';
};

export type DeleteApiV1AccountsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetApiV1AccountsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The id of the last item from the previous page
         */
        id?: string;
        /**
         * The date of the last item from the previous page
         */
        updatedAt?: string;
        /**
         * Number of items to return per page
         */
        pageSize?: number;
        /**
         * Order of the items
         */
        orderBy?: 'asc' | 'desc';
        /**
         * Optional alias for pageSize, clamped by the API for safety
         */
        limit?: number;
    };
    url: '/api/v1/accounts';
};

export type GetApiV1AccountsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type DeleteApiV1GeoNotesData = {
    body: {
        data: Array<{
            /**
             * The id of the todo item
             */
            id: string;
            /**
             * The date of the last item from the previous page
             */
            updatedAt?: string;
            /**
             * Number of items to return per page
             */
            pageSize?: number;
            /**
             * Order of the items
             */
            orderBy?: 'asc' | 'desc';
            /**
             * Optional bbox in `west,south,east,north` format
             */
            bbox?: string;
            /**
             * Western longitude bound
             */
            west?: number;
            /**
             * Southern latitude bound
             */
            south?: number;
            /**
             * Eastern longitude bound
             */
            east?: number;
            /**
             * Northern latitude bound
             */
            north?: number;
            /**
             * Optional alias for pageSize, clamped by the API for safety
             */
            limit?: number;
            /**
             * Optional zoom bucket hint from the client for future sampling rules
             */
            zoomBucket?: 'broad' | 'medium' | 'close';
        }>;
    };
    path?: never;
    query?: never;
    url: '/api/v1/geo-notes';
};

export type DeleteApiV1GeoNotesResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetApiV1GeoNotesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The id of the last item from the previous page
         */
        id?: string;
        /**
         * The date of the last item from the previous page
         */
        updatedAt?: string;
        /**
         * Number of items to return per page
         */
        pageSize?: number;
        /**
         * Order of the items
         */
        orderBy?: 'asc' | 'desc';
        /**
         * Optional bbox in `west,south,east,north` format
         */
        bbox?: string;
        /**
         * Western longitude bound
         */
        west?: number;
        /**
         * Southern latitude bound
         */
        south?: number;
        /**
         * Eastern longitude bound
         */
        east?: number;
        /**
         * Northern latitude bound
         */
        north?: number;
        /**
         * Optional alias for pageSize, clamped by the API for safety
         */
        limit?: number;
        /**
         * Optional zoom bucket hint from the client for future sampling rules
         */
        zoomBucket?: 'broad' | 'medium' | 'close';
    };
    url: '/api/v1/geo-notes';
};

export type GetApiV1GeoNotesResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostApiV1GeoNotesAddData = {
    body: {
        /**
         * The title of the map message
         */
        title: string;
        /**
         * The content of the map message
         */
        geoNote: string;
        /**
         * Latitude of the map message
         */
        latitude: number;
        /**
         * Longitude of the map message
         */
        longitude: number;
        /**
         * Optional URL of a video associated with the map message
         */
        videoUrl?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/geo-notes/add';
};

export type PostApiV1GeoNotesAddResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PutApiV1GeoNotesUpdateData = {
    body: {
        data: Array<{
            /**
             * The id of the todo item
             */
            id: string;
            /**
             * The new title of the todo item
             */
            title?: string;
            /**
             * The content of the map message
             */
            geoNote: string;
            /**
             * Optional URL of a video associated with the map message
             */
            videoUrl?: string;
            /**
             * The date of the last item from the previous page
             */
            updatedAt?: string;
            /**
             * Number of items to return per page
             */
            pageSize?: number;
            /**
             * Order of the items
             */
            orderBy?: 'asc' | 'desc';
            /**
             * Optional bbox in `west,south,east,north` format
             */
            bbox?: string;
            /**
             * Western longitude bound
             */
            west?: number;
            /**
             * Southern latitude bound
             */
            south?: number;
            /**
             * Eastern longitude bound
             */
            east?: number;
            /**
             * Northern latitude bound
             */
            north?: number;
            /**
             * Optional alias for pageSize, clamped by the API for safety
             */
            limit?: number;
            /**
             * Optional zoom bucket hint from the client for future sampling rules
             */
            zoomBucket?: 'broad' | 'medium' | 'close';
        }>;
    };
    path?: never;
    query?: never;
    url: '/api/v1/geo-notes/update';
};

export type PutApiV1GeoNotesUpdateResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetApiV1PermissionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The id of the last item from the previous page
         */
        id?: string;
        /**
         * The date of the last item from the previous page
         */
        updatedAt?: string;
        /**
         * Number of items to return per page
         */
        pageSize?: number;
        /**
         * Order of the items
         */
        orderBy?: 'asc' | 'desc';
        /**
         * Optional alias for pageSize, clamped by the API for safety
         */
        limit?: number;
    };
    url: '/api/v1/permissions';
};

export type GetApiV1PermissionsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostApiV1PermissionsCreateData = {
    body: {
        resource: string;
        key: string;
        action: 'create' | 'read' | 'update' | 'delete';
    };
    path?: never;
    query?: never;
    url: '/api/v1/permissions/create';
};

export type PostApiV1PermissionsCreateResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PatchApiV1PermissionsUpdateData = {
    body: {
        id: string;
        resource?: string;
        key?: string;
        action?: 'create' | 'read' | 'update' | 'delete';
        roleId?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/permissions/update';
};

export type PatchApiV1PermissionsUpdateResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type DeleteApiV1PermissionsDeleteData = {
    body: {
        /**
         * Permission id's
         */
        ids: Array<string>;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/permissions/delete';
};

export type DeleteApiV1PermissionsDeleteResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetApiV1RolesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The id of the last item from the previous page
         */
        id?: string;
        /**
         * The date of the last item from the previous page
         */
        updatedAt?: string;
        /**
         * Number of items to return per page
         */
        pageSize?: number;
        /**
         * Order of the items
         */
        orderBy?: 'asc' | 'desc';
        /**
         * Optional alias for pageSize, clamped by the API for safety
         */
        limit?: number;
    };
    url: '/api/v1/roles';
};

export type GetApiV1RolesResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostApiV1RolesCreateData = {
    body: {
        roleName: string;
        description: string;
        /**
         * Role permissions
         */
        permissions?: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/api/v1/roles/create';
};

export type PostApiV1RolesCreateResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PatchApiV1RolesUpdateData = {
    body: {
        /**
         * Role id.
         */
        roleId: string;
        roleName?: string;
        description?: string;
        /**
         * Optional role permissions.
         */
        permissions?: Array<string> | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/roles/update';
};

export type PatchApiV1RolesUpdateResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type DeleteApiV1RolesDeleteData = {
    body: {
        /**
         * Permission id's
         */
        ids: Array<string>;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/roles/delete';
};

export type DeleteApiV1RolesDeleteResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type DeleteApiV1TodosData = {
    body: {
        /**
         * Todo's id's
         */
        ids: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/api/v1/todos';
};

export type DeleteApiV1TodosResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetApiV1TodosData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The id of the last item from the previous page
         */
        id?: string;
        /**
         * The date of the last item from the previous page
         */
        updatedAt?: string;
        /**
         * Number of items to return per page
         */
        pageSize?: number;
        /**
         * Order of the items
         */
        orderBy?: 'asc' | 'desc';
        /**
         * Optional alias for pageSize, clamped by the API for safety
         */
        limit?: number;
    };
    url: '/api/v1/todos';
};

export type GetApiV1TodosResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostApiV1TodosAddData = {
    body: {
        /**
         * Todo title
         */
        title: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/todos/add';
};

export type PostApiV1TodosAddResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PutApiV1TodosUpdateData = {
    body: Array<{
        /**
         * The id of the todo item
         */
        id: string;
        /**
         * The new title of the todo item
         */
        title?: string;
        /**
         * The new completion status of the todo item
         */
        completed?: boolean;
    }>;
    path?: never;
    query?: never;
    url: '/api/v1/todos/update';
};

export type PutApiV1TodosUpdateResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetApiV1UserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/user';
};

export type GetApiV1UserResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostApiV1UserCreateData = {
    body: {
        firstName: string;
        lastName: string;
        email: string;
        password: string;
        roleId: string;
        /**
         * Optional user avatar image file buffer
         */
        image?: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/v1/user/create';
};

export type PostApiV1UserCreateResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PatchApiV1UserUpdateData = {
    body: {
        userId: string;
        firstName?: string;
        lastName?: string;
        email?: string;
        password?: string;
        roleId?: string;
        /**
         * Optional user avatar image file buffer or string representation
         */
        image?: unknown | string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/user/update';
};

export type PatchApiV1UserUpdateErrors = {
    /**
     * Default Response
     */
    400: {
        /**
         * Bad request error message
         */
        error: string;
    };
    /**
     * Default Response
     */
    401: {
        /**
         * Unauthorized error message
         */
        error: string;
    };
    /**
     * Default Response
     */
    403: {
        /**
         * Forbidden error message
         */
        error: string;
        message?: string;
    };
    /**
     * Default Response
     */
    500: {
        /**
         * Internal Server Error message
         */
        error: string;
    };
};

export type PatchApiV1UserUpdateError = PatchApiV1UserUpdateErrors[keyof PatchApiV1UserUpdateErrors];

export type PatchApiV1UserUpdateResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        name: string;
        firstName: string;
        lastName: string;
        email: string;
        image: string | null;
        emailVerified: boolean;
        /**
         * User creation date
         */
        createdAt: string;
        /**
         * User last update date
         */
        updatedAt: string;
    };
};

export type PatchApiV1UserUpdateResponse = PatchApiV1UserUpdateResponses[keyof PatchApiV1UserUpdateResponses];

export type GetApiV1UserAccessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/user/access';
};

export type GetApiV1UserAccessErrors = {
    /**
     * Default Response
     */
    401: {
        /**
         * Unauthorized error message
         */
        error: string;
    };
    /**
     * Default Response
     */
    403: {
        /**
         * Forbidden error message
         */
        error: string;
        message?: string;
    };
    /**
     * Default Response
     */
    500: {
        /**
         * Internal Server Error message
         */
        error: string;
    };
};

export type GetApiV1UserAccessError = GetApiV1UserAccessErrors[keyof GetApiV1UserAccessErrors];

export type GetApiV1UserAccessResponses = {
    /**
     * Default Response
     */
    200: {
        id: string | null;
        role: string | null;
        permissions: Array<string>;
    };
};

export type GetApiV1UserAccessResponse = GetApiV1UserAccessResponses[keyof GetApiV1UserAccessResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:3006' | (string & {});
};